version: 2.1
orbs:
  node: circleci/node@1.1.6
executors:
  default:
    docker:
      - image: cypress/base
    working_directory: ~/authtemplate
    environment:
      PROJECT_NAME: authtemplate
      API_URI: http://localhost:3000
      API_PORT: 3000
      DB_URI: mongodb://localhost:27027
      FRONT_URI: http://localhost:4200 
      JWT_KEY: authtemplate
      SALT_FACTOR: 10
jobs:
  build-test-back:
    executor: default
    docker:
      - image: cypress/base
      - image: circleci/mongo
        port: 27017:27017
        environment:
          MONGODB_DATABASE: authtemplate
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            if [ ! -f docker-17.03.0-ce.tgz ]; then
              curl -sLO https://download.docker.com/linux/static/stable/x86_64/docker-17.03.0-ce.tgz
            fi
            tar -xz -C /tmp -f docker-17.03.0-ce.tgz
            mv /tmp/docker/* /usr/bin
      # - run: docker run --name mongodb -p 27027:27027 -d mongo
      - run:
        name: Waiting for Mongo
        command: dockerize -wait tcp://localhost:27017 -timeout 1m
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build:back
            - run: npm run test:back
      
  build-test-front:
    executor: default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build:front
            - run: npm run test:front

workflows:
    build-and-test:
      jobs:
        - build-test-back
        - build-test-front