version: 2.1
orbs:
  node: circleci/node@1.1.6
executors:
  default:
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    working_directory: ~/authtemplate
    environment:
      PROJECT_NAME: authtemplate
      API_URI: http://localhost:3000
      API_PORT: 3000
      DB_URI: mongodb://localhost:27017/authtemplate
      FRONT_URI: http://localhost:4200 
      JWT_KEY: authtemplate
      SALT_FACTOR: 10
jobs:
  build-test-back:
    executor: default
    docker:
      - image: cypress/base
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build:back
            - run: npm run test:back
      
  build-test-front:
    executor: default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build:front
            - run: npm run test:front

workflows:
    build-and-test:
      jobs:
        - build-test-back
        - build-test-front